version: "3.7"

services:
  postgres_cadastro:
    container_name: postgres_cadastro_efood
    image: postgres:12
    environment: 
      POSTGRES_USER: efood_cadastro
      POSTGRES_PASSWORD: efood_cadastro
      POSTGRES_DB: efood
    ports:
      - "5432:5432"

  postgres_marketplace:
    container_name: postgres_marketplace_efood
    image: postgres:12
    environment: 
      POSTGRES_USER: efood_marketplace
      POSTGRES_PASSWORD: efood_marketplace
      POSTGRES_DB: efood
    ports:
      - "5433:5432"
  
  keycloak_efood:
    container_name: keycloak_efood
    image: jboss/keycloak:11.0.2
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"      
      
  jaeger_efood:
    container_name: jaeger_efood
    image: jaegertracing/all-in-one:1.19.2
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"      
      
  prometheus_efood:
    container_name: prometheus_efood
    image: prometheus-efood
    network_mode: "host"
    
  grafana_efood:
    container_name: grafana_efood
    image: grafana/grafana:7.2.0
#    image: grafana/grafana:6.5.0
    network_mode: "host"      
    
  artemis_efood:
    container_name: artemis_efood
    image: vromero/activemq-artemis:2.15.0
#    image: activemq-debian
    network_mode: "host"
    environment: 
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin    
      
  mongodb_efood:
    container_name: mongodb_efood
    image: mongo:4.2.10-bionic
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: efood_pedido
      MONGO_INITDB_ROOT_PASSWORD: efood_pedido
      MONGO_INITDB_DATABASE: efood      
      