version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro
    image: postgres:12
    environment: 
      POSTGRES_USER: efood_cadastro
      POSTGRES_PASSWORD: efood_cadastro
      POSTGRES_DB: efood
    ports:
      - "5432:5432"
  
  keycloak_efood:
    container_name: keycloak_efood
    image: jboss/keycloak:11.0.2
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"      