-- DROP TABLE public.pratos;

CREATE TABLE public.pratos (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	descricao varchar(255) NULL,
	nome varchar(255) NULL,
	preco numeric(19,2) NULL,
	restaurante_id int8 NULL,
	CONSTRAINT pratos_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.pratos OWNER TO efood_cadastro;
GRANT ALL ON TABLE public.pratos TO efood_cadastro;


-- public.pratos foreign keys

ALTER TABLE public.pratos ADD CONSTRAINT fknxpcllno0jo7d527g3cc2ro7r FOREIGN KEY (restaurante_id) REFERENCES restaurantes(id);
