-- DROP TABLE public.restaurantes;

CREATE TABLE public.restaurantes (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cnpj varchar(255) NULL,
	dataatualizacao timestamp NULL,
	datacriacao timestamp NULL,
	nome varchar(255) NULL,
	proprietario varchar(255) NULL,
	localizacao_id int8 NULL,
	CONSTRAINT restaurantes_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.restaurantes OWNER TO efood_cadastro;
GRANT ALL ON TABLE public.restaurantes TO efood_cadastro;


-- public.restaurantes foreign keys

ALTER TABLE public.restaurantes ADD CONSTRAINT fkpqs8jqjybpysyhhuru7dq4xo6 FOREIGN KEY (localizacao_id) REFERENCES localizacoes(id);
